export const HOMELAND_DEFENSE_BUFF = {
  id: "xHfo6Ztb-ZoElUsK",
  owner: "xHfo6Ztb-ZoElUsK",
  ownerDescription: "Родная земля",
  type: "battlefield",
  player: null,
  target: "player",
  appliedOn: "homeland",
  targetType: "unit",
  units: [
    "porter",
    "swordsman",
    "cavalier",
    "flying",
    "archer",
    "healer",
    "mercenary",
    "mage",
  ],
  title: "Защита родной земли",
  property: "defense",
  valueIndex: 0,
  value: [25],
  description: ["Защита родной земли +25"],
  battle: true,
};

export const BATTLEFIELD_ATTACK_BUFF = {
  id: "ZIFAO43CldB3Z8pN",
  owner: "ZIFAO43CldB3Z8pN",
  ownerDescription: "Террайн",
  type: "battlefield",
  player: null,
  target: "player",
  appliedOn: "battlefieldAttack",
  targetType: "unit",
  units: ["swordsman", "cavalier", "flying", "archer", "mercenary"],
  title: "Атака на террайне",
  property: "attackRate",
  valueIndex: 0,
  value: [0.5, -0.5],
  description: ["Атака на терайне +50%", "Атака на терайне -50%"],
  battle: true,
};

export const APOSTATE_ATTACK_BUFF = {
  id: "v0Bokc6Cx4_2SzzW",
  owner: "v0Bokc6Cx4_2SzzW",
  ownerDescription: "Дисбонус фракции",
  type: "race",
  player: null,
  target: "player",
  appliedOn: "apostate",
  targetType: "unit",
  units: [
    "swordsman",
    "cavalier",
    "flying",
    "archer",
    "healer",
    "mercenary",
    "mage",
  ],
  title: "Дисбонус атаки на свою фракцию",
  property: "attackRate",
  valueIndex: 0,
  value: [-0.25, -0.5],
  description: ["Атака на свою фракцию -25%", "Атака на свою рассу -50%"],
  battle: true,
};
